### ISSUE TITLE
cache:clear does not work

### ISSUE THREAD

**Issue by luxifer** [lexik/LexikTranslationBundle#142]
Hi,

Since the upgrade to Symfony 2.7, the `cache:clear` command does not work. Here's a sample output

```
Clearing the cache for the dev environment with debug true
  Warming up cache



  [Doctrine\DBAL\Exception\ConnectionException]
  An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory



Exception trace:
 () at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103
 Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php:133
 Doctrine\DBAL\DBALException::driverException() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:47
 Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
 Doctrine\DBAL\Connection->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
 Doctrine\DBAL\Connection->getDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:763
 Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:632
 Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:174
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
 Doctrine\ORM\EntityManager->getClassMetadata() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Storage/DoctrineORMStorage.php:22
 Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage->translationsTablesExist() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/EventDispatcher/GetDatabaseResourcesListener.php:41
 Lexik\Bundle\TranslationBundle\EventDispatcher\GetDatabaseResourcesListener->onGetDatabaseResources() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
 Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:124
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Translation/Translator.php:28
 Lexik\Bundle\TranslationBundle\Translation\Translator->addDatabaseResources() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:2184
 xoteli_DevDebugProjectContainer->getLexikTranslation_TranslatorService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:509
 xoteli_DevDebugProjectContainer->getCacheWarmerService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2626
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2396
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/florent/apps/xotelia/app/console:33





  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000] [2002] No such file or directory



Exception trace:
 () at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47
 Doctrine\DBAL\Driver\PDOConnection::__construct() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:45
 Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
 Doctrine\DBAL\Connection->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
 Doctrine\DBAL\Connection->getDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:763
 Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:632
 Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:174
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
 Doctrine\ORM\EntityManager->getClassMetadata() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Storage/DoctrineORMStorage.php:22
 Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage->translationsTablesExist() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/EventDispatcher/GetDatabaseResourcesListener.php:41
 Lexik\Bundle\TranslationBundle\EventDispatcher\GetDatabaseResourcesListener->onGetDatabaseResources() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
 Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:124
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Translation/Translator.php:28
 Lexik\Bundle\TranslationBundle\Translation\Translator->addDatabaseResources() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:2184
 xoteli_DevDebugProjectContainer->getLexikTranslation_TranslatorService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:509
 xoteli_DevDebugProjectContainer->getCacheWarmerService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2626
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2396
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/florent/apps/xotelia/app/console:33





  [PDOException]
  SQLSTATE[HY000] [2002] No such file or directory



Exception trace:
 () at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 PDO->__construct() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43
 Doctrine\DBAL\Driver\PDOConnection->__construct() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php:45
 Doctrine\DBAL\Driver\PDOMySql\Driver->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:360
 Doctrine\DBAL\Connection->connect() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:429
 Doctrine\DBAL\Connection->getDatabasePlatformVersion() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:389
 Doctrine\DBAL\Connection->detectDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php:328
 Doctrine\DBAL\Connection->getDatabasePlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:763
 Doctrine\ORM\Mapping\ClassMetadataFactory->getTargetPlatform() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:632
 Doctrine\ORM\Mapping\ClassMetadataFactory->completeIdGeneratorMapping() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:174
 Doctrine\ORM\Mapping\ClassMetadataFactory->doLoadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:332
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php:78
 Doctrine\ORM\Mapping\ClassMetadataFactory->loadMetadata() at /Users/florent/apps/xotelia/vendor/doctrine/common/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php:216
 Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory->getMetadataFor() at /Users/florent/apps/xotelia/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php:281
 Doctrine\ORM\EntityManager->getClassMetadata() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Storage/DoctrineORMStorage.php:22
 Lexik\Bundle\TranslationBundle\Storage\DoctrineORMStorage->translationsTablesExist() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/EventDispatcher/GetDatabaseResourcesListener.php:41
 Lexik\Bundle\TranslationBundle\EventDispatcher\GetDatabaseResourcesListener->onGetDatabaseResources() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php:61
 Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke() at n/a:n/a
 call_user_func() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:164
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:53
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php:167
 Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php:124
 Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch() at /Users/florent/apps/xotelia/vendor/lexik/translation-bundle/Lexik/Bundle/TranslationBundle/Translation/Translator.php:28
 Lexik\Bundle\TranslationBundle\Translation\Translator->addDatabaseResources() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:2184
 xoteli_DevDebugProjectContainer->getLexikTranslation_TranslatorService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/.software/.cache/de_/xoteli_DevDebugProjectContainer.php:509
 xoteli_DevDebugProjectContainer->getCacheWarmerService() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2140
 Symfony\Component\DependencyInjection\Container->get() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2626
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/florent/apps/xotelia/app/bootstrap.php.cache:2396
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:128
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->warmup() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Command/CacheClearCommand.php:90
 Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand->execute() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:886
 Symfony\Component\Console\Application->doRunCommand() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:96
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/florent/apps/xotelia/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/florent/apps/xotelia/app/console:33


cache:clear [--no-warmup] [--no-optional-warmers]
```

It seems the bunle tries to check if database exists but on a fresh install (deploy) of the project on CI for exemple, the database is not created, no vendors are installed. I cannot do a `doctrine:schema:update` before installing the vendors ^^ Also the translations are not mandatory to the system since there are files.

I noticed in `Lexik\Bundle\TranslationBundle\EventDispatcher\GetDatabaseResourcesListener` there's a check for the schema, but what about the database?

Thanks

**Comment by lologhi** [comment]
Hi! Same problem here, I'm stuck with Travis :disappointed:

**Comment by luxifer** [comment]
Ensure your database engine is running and the database is created

Florent Viel

**Comment by lologhi** [comment]
Ok, but, on a fresh install, I can manually create the database. But when I `composer install`, the schema is missing, and it fails while querying `lexis_trans_unit`...

**Comment by luxifer** [comment]
you can do a `composer install --no-scripts`, then update the schema, then clear the cache

**Comment by lologhi** [comment]
Woaw ! Great ! Thanks a lot for you help :-)

**Comment by lologhi** [comment]
My mistake, same `lexik_trans_unit doesn't exist` error message for `php app/console doctrine:schema:create`... Are there a command to create `lexik_trans_unit`?

**Comment by velikanov** [comment]
:+1:
I have Doctrine DBAL called, but I have storage.type: mongodb

weird…

  [Doctrine\DBAL\Schema\SchemaException]
  There is no column with name 'locale' on table 'lexik_trans_unit_translations'.

**Comment by lyrixx** [comment]
Hello.

I don't know this project (I'm helping a colleague to deploy its project).

But because of this bundle, it's not possible to deploy it with ease on a new server because your bundle try to connect to the DB during the kernel boot.
And So it's not possible to create the database with Symfony because the database does not exist yet.
We have a chicken and egg problem here.

IMHO, you should remove all this magic layer, and document how to install your bundle and keep in a regular symfony.

**Comment by cedric-g** [comment]
Can you have a try with the latest version on master, it should be fixed for Doctrine ORM.

**Comment by luxifer** [comment]
Still have the problem with `doctrine:database:create` (on the latest stable release `v3.1.1`)

**Comment by cedric-g** [comment]
I've not tagged the fix yet so try with `dev-master`.

**Comment by lyrixx** [comment]
Thanks for tour work. Unfortunately I cannot test it anymore since it was not my project :-(  but I will ping my coworker

**Comment by mpoiriert** [comment]
Still ocuring !

**Comment by coala** [comment]
see pull request #214
