### ISSUE TITLE
Class not found in Symfony 2.5.2

### ISSUE THREAD

**Issue by arkaitzgarro** [lexik/LexikTranslationBundle#83]
After installing the bundle with composer and registering it in AppKernel.php, I get the following error when I try to update de database schema:

```
MappingException: The class 'Lexik\Bundle\TranslationBundle\Entity\TransUnit' was not found in the chain configured namespaces...
```

I'm using 1.4 branch. Any ideas?

**Comment by arkaitzgarro** [comment]
Hi @vadimsauzans,

With this solution, you have disabled the Doctrine automaping, so the rest of the bundles are not loading the mappings. Anyway, this this solution, I'm still getting the same error.

Why doctrine is still not finding the entity?

![screen shot 2015-01-21 at 09 39 07](https://cloud.githubusercontent.com/assets/1712467/5833349/c325afec-a152-11e4-86f7-c96910dbadd5.png)

**Comment by cedric-g** [comment]
This kind of error should be fixed on `master` since https://github.com/lexik/LexikTranslationBundle/commit/cb5f2a0d932c932306c105bb709acdc7372e6726.

**Comment by arkaitzgarro** [comment]
Still not working for me on `master` branch. I don't know, but maybe I have something wrong in my Doctrine config.

**Comment by arkaitzgarro** [comment]
OK, it works on a clean Symfony installation.
